apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 879772956301.dkr.ecr.us-west-1.amazonaws.com/m-6th-t24-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: APP_CORS_ALLOWED_ORIGINS
              value: "*"
