server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /books {
        proxy_pass http://backend:8080/books;
    }

    location /auth {
        proxy_pass http://backend:8080/auth;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}